export function throw_error() {
	throw new Error("Throw exception test")
}

